name: Build
on: push
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell -p '(nixos{}).nixos-rebuild dry-run'
