name: Build
on: push
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

        # read <https://nixos.wiki/wiki/Nixos-rebuild>
      - run: ./init.sh
      - run: nix-shell -p '(nixos{}).nixos-rebuild' --run 'nixos-rebuild dry-run -I nixos-config=./configuration.nix'
