name: Checks
on: 
  - push
  - pull_request

jobs:
  deadnix:
    name: "Dead Nix"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell -p deadnix --run 'deadnix .'
  nixpkgs-fmt:
    name: "Check format"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/installi-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell -p nixpkgs-fmt --run "nixpkgs-fmt --check ."

