name: Scheduled Update
on:
  schedule:
    - cron: "0 0 * * sun"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # go to Account / Settings > Developer Settings > Personal access tokens
          # then create one with permission: Content WRITE
          token: ${{ secrets.SELF_CONTENT_WRITE_TOKEN }}
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: "nixpkgs=flake:nixpkgs"
      - run: nix flake update
      - run: nix build .#nixosConfigurations.amberwood.activationPackage --no-link
      - uses: EndBug/add-and-commit@v9
        with:
          message: "(bot)schedule: update flake"
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
